version: "3.7"
services:
  app:
    build:
      args:
        user: alisalehi
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: 7learn
    container_name: 7learn-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - 7learn


  db:
    image: mysql:8.0
    container_name: 7learn-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./services/mysql:/docker-entrypoint-initdb.d
    networks:
      - 7learn

  nginx:
    image: nginx:alpine
    container_name: 7learn-nginx
    restart: unless-stopped
    ports:
      - 1212:80
    volumes:
      - ./:/var/www
      - ./services/nginx:/etc/nginx/conf.d/
    networks:
      - 7learn

  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: 7learn-phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - 8081:80
    networks:
      - 7learn
    depends_on:
      - db

networks:
  7learn:
    driver: bridge